# Generated by Django 6.0.1 on 2026-01-09 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("library", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StreakRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_practice_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Streak Record",
                "verbose_name_plural": "Streak Records",
            },
        ),
        migrations.CreateModel(
            name="PhonemeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_score",
                    models.FloatField(
                        default=0,
                        help_text="Most recent average score for this phoneme",
                    ),
                ),
                ("attempts_count", models.IntegerField(default=0)),
                ("first_attempt_score", models.FloatField(blank=True, null=True)),
                ("best_score", models.FloatField(blank=True, null=True)),
                (
                    "improvement_rate",
                    models.FloatField(
                        default=0, help_text="Score improvement per 10 attempts"
                    ),
                ),
                ("first_practiced", models.DateTimeField(blank=True, null=True)),
                ("last_practiced", models.DateTimeField(blank=True, null=True)),
                (
                    "phoneme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="library.phoneme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phoneme_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Phoneme Progress",
                "verbose_name_plural": "Phoneme Progress Records",
                "ordering": ["user", "phoneme"],
                "unique_together": {("user", "phoneme")},
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("sessions_count", models.IntegerField(default=0)),
                ("total_practice_minutes", models.FloatField(default=0)),
                ("attempts_count", models.IntegerField(default=0)),
                ("average_score", models.FloatField(blank=True, null=True)),
                ("best_score", models.FloatField(blank=True, null=True)),
                (
                    "weak_phonemes",
                    models.JSONField(
                        default=list, help_text="List of weak phonemes for this day"
                    ),
                ),
                (
                    "improved_phonemes",
                    models.JSONField(
                        default=list,
                        help_text="Phonemes that improved compared to previous day",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Progress",
                "verbose_name_plural": "User Progress Records",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
