# Generated by Django 6.0.1 on 2026-01-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordresettoken",
            name="token",
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="token_hash",
            field=models.CharField(
                default="placeholder_hash_invalidate_existing",
                help_text="SHA-256 hash of the reset token",
                max_length=64,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
