# Generated by Django 6.0.1 on 2026-01-09 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("library", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="user_uploads/"),
                ),
                (
                    "audio_url",
                    models.URLField(blank=True, help_text="Supabase storage URL"),
                ),
                (
                    "score",
                    models.FloatField(help_text="Overall pronunciation score (0-1)"),
                ),
                (
                    "fluency_score",
                    models.FloatField(
                        blank=True, help_text="Fluency/timing score (0-1)", null=True
                    ),
                ),
                (
                    "phoneme_scores",
                    models.JSONField(
                        blank=True,
                        help_text='Per-phoneme scores: [{"phoneme": "S", "score": 0.92}]',
                        null=True,
                    ),
                ),
                (
                    "llm_feedback",
                    models.JSONField(
                        blank=True,
                        help_text="LLM feedback: {summary, phoneme_tips, encouragement}",
                        null=True,
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Total processing time in milliseconds",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_attempts",
                        to="library.referencesentence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attempt",
                "verbose_name_plural": "Attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhonemeError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_vector",
                    models.BinaryField(
                        blank=True,
                        help_text="Reference phoneme embedding (serialized numpy)",
                        null=True,
                    ),
                ),
                (
                    "user_vector",
                    models.BinaryField(
                        blank=True,
                        help_text="User pronunciation embedding (serialized numpy)",
                        null=True,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(help_text="Cosine similarity (0-1)"),
                ),
                (
                    "word_context",
                    models.CharField(
                        help_text="Word containing the phoneme", max_length=100
                    ),
                ),
                (
                    "position_in_word",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("medial", "Medial"),
                            ("final", "Final"),
                        ],
                        default="medial",
                        max_length=20,
                    ),
                ),
                (
                    "start_time",
                    models.FloatField(
                        blank=True, help_text="Start time in audio (seconds)", null=True
                    ),
                ),
                (
                    "end_time",
                    models.FloatField(
                        blank=True, help_text="End time in audio (seconds)", null=True
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phoneme_errors",
                        to="practice.attempt",
                    ),
                ),
                (
                    "target_phoneme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_errors",
                        to="library.phoneme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phoneme Error",
                "verbose_name_plural": "Phoneme Errors",
                "ordering": ["attempt", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("practice", "Practice"),
                            ("assessment", "Assessment"),
                            ("warmup", "Warmup"),
                        ],
                        default="practice",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("overall_score", models.FloatField(blank=True, null=True)),
                ("total_attempts", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="attempt",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="practice.usersession",
            ),
        ),
    ]
